### ISSUE TITLE
solana_signTransaction error

### ISSUE THREAD

**Issue by Xing94** [WalletConnect/WalletConnectKotlinV2#348]
solana_ The returned data of signtransaction method is error

**Comment by Elyniss** [comment]
Thanks for creating an issue. In order to move forward with the bug report, we need more details. Please fill the form below:

**Describe the bug**
A clear and concise description of what the bug is.

**SDK Version**
 - Client: [e.g.  Kotlin]
 - Version [e.g. 22]

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.


**Device (please complete the following information):**
 - Device: [e.g. Pixel]
 - OS: [e.g. Android 12]
 - Browser [e.g. stock browser, chrome]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
