### ISSUE TITLE
Allow downloading the source code from MC

### ISSUE THREAD

**Issue by Elyniss** [WalletConnect/WalletConnectKotlinV2#463]
- Check if removing jitpack artifacts help

**Comment by jakobuid** [comment]
Discussion: https://github.com/WalletConnect/walletconnect-monorepo/discussions/1584?sort=old

**Comment by jakobuid** [comment]
The task is on hold.

Checked, but it did not help:
- Added .version file to the META-INF of Chat SDK
- Added the ext for @aar in the implementation when fetching dependency
- Researched a bunch of errors: `org.gradle.internal.resolve.ModuleVersionResolveException`, `org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException`, `Task ':app:DownloadSources' is not up-to-date because: Task has not declared any outputs despite executing action`

Updates:
- Updated docs with new maven URLs (`maven { url '[https://jitpack.io](https://jitpack.io/)' }`, `maven { url "https://repo1.maven.org/maven2/" }`)

Observation:
The problem occurs in both situations when the artifact is fetched from maven central and when an old artifact is fetched from jitpack.

**Comment by jakobuid** [comment]
Reported issue: https://github.com/WalletConnect/WalletConnectKotlinV2/issues/494
