### ISSUE TITLE
There is no success callback for SignClient.respond()

### ISSUE THREAD

**Issue by clj12081103** [WalletConnect/WalletConnectKotlinV2#530]
```
SignClient.respond(result) { error ->
                Log.e(tag(this), error.throwable.stackTraceToString())
            }
```
```
fun respond(response: Sign.Params.Response, onError: (Sign.Model.Error) -> Unit)
```
only error callback, no success callback

**Comment by TalhaAli00** [comment]
Can you describe your use-case where you would want something returned in a success callback? The function was intended to be a fire and forget function.

**Comment by Elyniss** [comment]
Added to our prioritised kanban board

**Comment by mitsinsar** [comment]
Hi @Elyniss , is it going to be `respond()` only or will `success callback` be supported for all functions, like `extend`, `disconnect`? 

I have trust issues and would like to know if it is `success` or `not`. Joke aside, we take action based on `success` callback a lot, that's why we need this callback for every function that has interaction with dApp. 

Also, appx when will you implement this enhancement? Based on your answer, I may need to fork and update accordingly by myself. 

Thanks!
