### ISSUE TITLE
Update session with new chain id not work

### ISSUE THREAD

**Issue by ludowkm** [WalletConnect/WalletConnectKotlinV2#554]
From the documentation, it's allow to update session with new chain from wallet
https://docs.walletconnect.com/2.0/swift/sign/wallet-usage#update-session

Step to reproduce:
I did update namespaces with new chain id and call update session.
For e.g: "eip155:1:0x...99" to "eip155:56:0x..99"
I tried with https://react-app.walletconnect.com

On iOS side:
The above example dapp's chain has been changed, but wallet did not receive any session update so the local storage was not updated

On Android side:
There is an exception, i checked the source code and saw that there is a validation to check that new chain id with the original chain id from session proposal, so it does not make sense.

There is a different between platforms so i think we need to correct it.

**Comment by jakobuid** [comment]
Hey, the validation on the Android side seems to work as expected. In order to update namespaces with new accounts, the given set of accounts should be on at least one of the chains in the required namespaces received in the session proposal.

The update of the namespaces should match chains from the required namespaces, if this requirement is satisfied you can add of course more accounts on different chains.

When it comes to required namespaces you can think of them as the min requirements that the wallet should satisfy to have an active connection with a Dapp.

Here you can find more info about this concept with all validation test cases: https://docs.walletconnect.com/2.0/specs/clients/sign/session-namespaces

It's seems that the iOS implementation might be off, the iOS team is already aware if it but I recommend adding an issue to: https://github.com/WalletConnect/WalletConnectSwiftV2/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by jakobuid** [comment]
To ensure that this feature works as expected you can share the proposal namespaces payload that is received from a dapp and the one that you try to update with. So that I can provide it to our tests and see the result.
